name: Latest blog post workflow from Medium
on:
  schedule: # Run workflow automatically
    - cron: '0 3 * * 1'
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@burakdev"
          max_post_count: "5"
